### ISSUE TITLE
Using slider with Angular material dialog.

### ISSUE THREAD

**Issue by rizerok** [angular-slider/ng5-slider#16]
Hello, thanks for slider.
But I have problem using slider with [material dialog](https://material.angular.io/components/dialog/overview). When dialog opened, slider incorrectly updates ceil ([example](https://stackblitz.com/edit/angular-material-range-slider)). How fix it?

**Comment by piotrdz** [comment]
Thanks for reporting this and providing an example to reproduce the issue.

From what I can see so far, this is another rendering issue which is caused by CSS changes affecting the component layout like the previously reported issue #15. I fixed the previous issue by providing a manual way of refreshing the slider geometry. It's not perfect but it works in cases like this one.

Now, for this case, I tried to use my workaround with manual refresh [in this fork of your example](https://stackblitz.com/edit/angular-material-range-slider-kxqxmq). However, it's not working as well as it should - you can see a lag between when the dialog is first displayed and when the sliders are refreshed. This is probably caused by Material using Angular animations to show/hide the dialog.

I will look more into what exactly is happening. There might be a patch that I can suggest to Material guys that will fix this.

**Comment by rizerok** [comment]
It seems bug is due to that component is initialized in the `setTimeout` earlier than `ngAfterViewInit`. If initialize component in `ngAfterViewInit`, the dimensions are calculated correctly. Apparently `this.init();` in `setTimeout` occurs in animation moment.

I solved my task [this way](https://stackblitz.com/edit/angular-material-range-slider-hack). But it's very dirty hack. I worked little with angular, but I think use setTimeout is bad idea. I tried to change 
```javascript
ngAfterViewInit(): void {
   ...
    setTimeout((): void => this.init();
    this.cd.detectChanges();
  }
setTimeout ((): void => this.init (), 0);
```
on 
```javascript
constructor(private cd: ChangeDetectorRef) { }
...
ngAfterViewInit(): void {
   ...
   this.init ();
   this.cd.detectChanges();
}
```
but got ExpressionChangedAfterItHasBeenCheckedError for disabled and vertical sliders.
Maybe this will help.

**Comment by piotrdz** [comment]
Thanks for investigating this further. I agree that the initialisation code could be written in more Angular-like fashion, but I'm afraid this is going to take a while to fix. It's not only disabled and vertical sliders that are affected, but it's the whole concept of positioning slider elements that's affected. I'll take another look at it once I have more time.

**Comment by piotrdz** [comment]
Good news. I was wrong and it was a simple fix. The issue with disabled and vertical sliders was the only problem and it was easily solved by moving the initialization of these settings to `ngOnInit()`. It looks all good and fixed in v1.1.3

**Comment by manueledones** [comment]
I think to have the same issue, [here the stackblitz](https://angular-material-range-slider-m4eua2.stackblitz.io)

If you open the modal dialog and change the slider, it's going to be repainted and the effect is not cool.

Is there any fixes? Thanks!

**Comment by VISHNUMURTHY** [comment]
This issue still exists w.r.t mat-dialog.. I am using angular 12 with "@angular-slider/ngx-slider": "2.0.4" 
![image](https://user-images.githubusercontent.com/14991239/179327316-648edc06-a6f6-4fa0-a36d-4729938fba10.png)

**Comment by ljnocca** [comment]
@VISHNUMURTHY - I'm running into the same issue in addition to getting NAN on the min value. Were you able to solve this by any chance?

**Comment by VISHNUMURTHY** [comment]
I found workaround for this issue first create template variable(#slider) for ngx-slider as below in html
<ngx-slider #slider [options]="col.options" [formControl]="control">
                </ngx-slider>

Inside component.ts get the access to template variable as below:
@ViewChildren('slider')
  sliders: QueryList<any>;

in ngAfterViewChecked life cycle add below code: here sliderLoaded will help you to avoid continuous template updates & changes if condition not added then you will ran into performance issue if page opened for longer time. Hence careful with this life cyle in my case ngAfterViewInit was not helpful as sliders generated dynamically. If your case is static content display then you can try with ngAfterViewInit life cycle also once.

  ngAfterViewChecked(): void {
    if (this.sliderLoaded) {
      if (this.sliders.length > 0) {
        this.sliders.forEach((slider: SliderComponent, i: number) => {
          setTimeout((slider: SliderComponent) => {
            slider.ngAfterViewInit(); //rerun the afterviewinit for ngx-slider to update component with latest changes.
            this.cdRef.detectChanges();
          }, 10, slider);
        });
        this.sliderLoaded = true;
      }
    }
  }

**Comment by ljnocca** [comment]
@VISHNUMURTHY - thanks does this solve the issues for both NAN and the max value initially being set in the wrong position?

**Comment by VISHNUMURTHY** [comment]
> @VISHNUMURTHY - I'm running into the same issue in addition to getting NAN on the min value. Were you able to solve this by any chance?

Nan value issue i didn't encountered.. In my case it's taking min & max values correctly as I am sending both min & max numerical values. Instead of null or undefined, I hope in your case min value would have been not valid numerical value.

**Comment by vangarsushil** [comment]
using EventEmitter we can solve this issue

html : 

  <div class="price-slider-wrapper" lines="none">
                            <ng5-slider color="primary" [(value)]="minPrice" [(highValue)]="maxPrice" 
                                         (userChange)="priceSliderChange($event)"
                                [options]="premoptions" (click)="$event.stopPropagation();"  [manualRefresh]="manualRefresh">
                            </ng5-slider>
 </div>



ts:

  public manualRefresh = new EventEmitter<void>();
 priceMenuOpen:boolean = false;

on menu click event called below function: 

  openPriceSlider(){
        this.priceMenuOpen = true;
        setTimeout(() => {
            this.manualRefresh.emit();
        }, 200);
    }

**Comment by Arkarion** [comment]
Problem still exists: 
<img width="580" alt="image" src="https://user-images.githubusercontent.com/125976483/220332504-ad6b238a-2a70-4594-8c40-f29a542c3df3.png">

Any news concerning this? Is there a solution that doesn't require to reload the component every time?

**Comment by nathkamal** [comment]
Or, you could simply override Css like below.

 ::ng-deep .ngx-slider-ceil {
        right:0 !important;
        left: auto !important;
    }
