### ISSUE TITLE
fix slider jumps to first value if value is not in stepsArray

### ISSUE THREAD

**Issue by dexbytesmanish** [angular-slider/ng5-slider#29]
Hi,
is this below mentioned issue also fixed in Angular 5 version of slider ?
https://github.com/angular-slider/angularjs-slider/pull/626

Please confirm or fix that also in this version.

**Comment by piotrdz** [comment]
The merge request in question hasn't been merged to angularjs-slider, so the issue was also present when I rewrote the code to Angular 5.

I fixed the problem presently with my own implementation. The slider will now jump to the first closest value.

**Comment by dexbytesmanish** [comment]
ok, thanks. Can you please also check and confirm that all other issues that were reported for angularjs-slider have been fixed for Angular 5 too regardless of their status in angularjs-slider repo ?

**Comment by piotrdz** [comment]
Closing as originally reported issue fixed with v1.1.4 ( [StackBlitz example](https://stackblitz.com/edit/ng5-slider-issue-29?file=src%2Fapp%2Fapp.component.ts) ).

**Comment by dexbytesmanish** [comment]
There is still one more issue remaing in this case. Slider is jumping to first closes value but that value is not being updated to model bindings hence model binded values are not showing updated values as the slider is actually having. Please check this ( [StackBlitz Example]) (https://stackblitz.com/edit/ng5-slider-issue-29-vh9erz) for the remaining issue.
