### ISSUE TITLE
Set formControl value manually doesn't update the view

### ISSUE THREAD

**Issue by guilhermenass** [angular-slider/ng5-slider#93]
I've problems to set values manually in formControl. On ngOnInit, I call this code to test:

`sliderControl: FormControl = new FormControl(360);`

`this.sliderControl.setValue(60)`

On my view HTML, the value 60min appears and it's ok. But the slider position, is on initial position, as you can see:

![image](https://user-images.githubusercontent.com/14130017/56922215-0901ca00-6a9e-11e9-916f-186a9afb675a.png)

The position didn't change. The expected behavior is:
![image](https://user-images.githubusercontent.com/14130017/56922266-2b93e300-6a9e-11e9-98e9-028bea4e3f3d.png).

My options:
```
 options: Options = {
    step: 30,
    floor: 0,
    ceil: 1439,
    showSelectionBar: true,

    getSelectionBarColor: (value: number): string => {
        if (value <= 150) {
            return 'green';
        }
        if (value <= 360) {
            return 'yellow';        }

        if (value <= 900) {
          return 'orange';
      }        
        if (value <= 1440) {
            return 'red';
        }
        return '#2AE02A';
    },

```

**I'm using this version of ng5-slider:
Version "ng5-slider": "^1.1.14",**

**Comment by guilhermenass** [comment]
It seems to be a problem with screen resolution. Can someone help me?
![problema ng5-slider](https://user-images.githubusercontent.com/14130017/56926005-0fe10a80-6aa7-11e9-8b6b-c37a99aa74e6.gif)

**Comment by frankie567** [comment]
Had the same issue, the solution is to use the `manualRefresh` feature. Bind the property to an observable, and make it emit at the end of `ngOnInit`:

```ts
public manualRefresh = new Subject<void>();

public ngOnInit(): void {
  // ...
  this.manualRefresh.next();
}
```

```html
<ng5-slider [(value)]=value [options]="options" [manualRefresh]="manualRefresh"></ng5-slider>
````

**Comment by guilhermenass** [comment]
@frankie567 Thanks for the response. But, I still need to use FormControl, like the example I gave? On your example, you create a subject<void>, I did'nt understand how to update the value.

**Comment by frankie567** [comment]
Well, as you stated in your first post, you correctly binded the value with the FormControl.

The `manualRefresh` thing I showed you has nothing to do with the value, it's a way to force `ng5-slider` to recalculate the elements position to avoid the screen resolution issue you showed. I use a `
void` Subject because we don't care about the value emitted in the refresh trigger, we just want a "stimulus".

Here is an example with a `FormControl`:

```ts
sliderControl: FormControl = new FormControl(100);
manualRefresh = new Subject<void>();

ngOnInit(): void {
  this.sliderControl.setValue(60)
  this.manualRefresh.next();
}
```

```html
<ng5-slider [options]="options" [formControl]="sliderControl" [manualRefresh]="manualRefresh"></ng5-slider>
```

**Comment by guilhermenass** [comment]
@frankie Thanks for the response. Now, I understand your example, but it's not working. The value appeared right, but slider position doesn't change. When I open the chrome tools (F12), the slider position changes to the right position.

**Comment by frankie567** [comment]
Maybe you can try to do `this.manualRefresh.next();` in the `ngOnChanges` hook?

**Comment by ReinerRunge** [comment]
Also facing the same issue. version 1.1.14.

The values are correct, but the slider position does not change. Only when adjusting the size of the screen or clicking the slider triggers a change.

I have this issue on init and I don't update the values dynamically either.

Triggering a `this.manualRefresh.next()` doesn't change the position of the slider on either `ngOnInit` or `ngOnChanges`

**Comment by dylanvdmerwe** [comment]
Note that we are also having this exact issue. Resizing the page updates the control to show the correct values. As per @ReinerRunge above.

**Comment by guilhermenass** [comment]
> Maybe you can try to do `this.manualRefresh.next();` in the `ngOnChanges` hook?

Hi Frank, it doesn't work for me. Thanks for the response!

**Comment by guilhermenass** [comment]
Some news for this problem??

**Comment by kurthamilton** [comment]
I'm having this issue too.

My very hacky workaround is to trigger a fake window resize event in my ngOnChanges function. Additionally, the event is only respected when run inside a timeout.

```javascript
ngOnChanges(): void {
  window.setTimeout(() => {
    window.dispatchEvent(new Event('resize'));
  }, 0);
}
```

**Comment by piotrdz** [comment]
In recent changes, I re-wrote most of value update and normalisation code using rxjs, fixing a lot of similar bugs.

This should be fixed once I make the next release in the next day or two.

**Comment by piotrdz** [comment]
Fix released with v1.2.0.

**Comment by AskmeKolaric** [comment]
I have v1.2.1 and i still have this same problem as other people

**Comment by IvanoAlvino** [comment]
Same, still have this problem

**Comment by edilson14** [comment]
still have this problem , any luck??

**Comment by steve-heine** [comment]
Is the problem that the values are strings instead of numeric?

**Comment by steve-heine** [comment]
Just an FYI, we found that this is in fact the issue. The library expects numeric values, but works for most use-cases with strings. We switched our values to numeric and this corrected this issue.
